### ISSUE TITLE
Status/Tool TIPS on Inputs ?

### ISSUE THREAD

**Issue by mattbeghin** [mrRay/ISF_Spec#1]
I want to suggest to add a way to document a bit an INPUT parameter so application is able to display it as a tooltip or status tip. For instance on "speed" parameter we could have "LABEL" entry with "Speed " and a "TIP" entry with "Speed of the animation. Set it to 0 to stop the animation, 1 for a 1 second animation loop etc."
What do you think ?

**Comment by mrRay** [comment]
sounds like a good idea, but how about we call it DESCRIPTION instead of TIP?

**Comment by mattbeghin** [comment]
Sure, DESCRIPTION is perfect !

**Comment by mrRay** [comment]
i added this to the v3 draft of the spec because at this point i think that's where new stuff and changes should probably be added, but there's no reason you need to hold off on using this if you'd like.  this is a very straightforward, simple, and logical addition.
