### ISSUE TITLE
Projects leveraging ISF

### ISSUE THREAD

**Issue by jcelerier** [mrRay/ISF_Spec#2]
Hey,
here are a few projects that use ISF if you want to add them to the list : 

- https://github.com/sophiadigitalart/ISFGif
- https://github.com/sophiadigitalart/ISFAblLinkSpoutOut (these guys have a few other nice projects leveraging ISF :p)

- I've started working on a C++ / Qt based editor (and ISF parsing library) on my spare time, which works on mac / linux / windows : https://github.com/jcelerier/libisf and has nice code completion (at least on linux). For the library though I'd like at some point to make something *truly* generic which would use [glslang](https://github.com/KhronosGroup/glslang) for putting ISF shaders in SPIR-V and [spirv-cross](https://github.com/KhronosGroup/spirv-cross) to be able to output them in any format, which would be useful for using ISF with newer graphics API - Metal (especially relevant with the GL deprecation in Apple platforms), D3D12 and of course Vulkan.

In any case great work with the spec, this makes writing shaders fun ;p

**Comment by mrRay** [comment]
howdy-

awesome, thanks for the links!  we're putting together a list of ISF implementations and experiments in a more public/user-facing location where they'll get more traffic, i'll add these to it:

http://docs.isf.video/#adding-support-for-isf-in-3rd-party-software
